### ISSUE TITLE
fs.copyfile is not a function

### ISSUE THREAD

**Issue by jingzheshan** [gregnb/filemanager-webpack-plugin#7]
Hi,

After updated to 1.0.14, it shows following error when running the plugin.

TypeError: fs.copyFile is not a function
    at C:\Projects\Web\Teams\node_modules\filemanager-webpack-plugin\lib\index.js:116:26
    at FSReqWrap.oncomplete (fs.js:114:15)

Thanks

**Comment by gregnb** [comment]
All set?

**Comment by jingzheshan** [comment]
Just realised my node.js is really out of date. Thanks dude.
