### ISSUE TITLE
Typescript error with 7.0.0-alpha.1

### ISSUE THREAD

**Issue by Phil147** [gregnb/filemanager-webpack-plugin#114]
## Issue
The simplest form like
```js
new FileManagerPlugin({
  events: {
     onEnd: {
        copy: [
          { source: '/path/fromfile.txt', destination: '/path/tofile.txt' },
          { source: '/path/**/*.js', destination: '/path' },
        ],
      }
   }
})

```
is not working with typescript and v7.0.0-alpha.1 anymore. Typescript will throw with:

```
error TS2322: Type '{ copy: { source: string; destination: string; }[]; }' is not assignable to type 'Actions | Actions[] | undefined'.
  Types of property 'copy' are incompatible.
    Type '{ source: string; destination: string; }[]' is not assignable to type 'Copy'.
      Type '{ source: string; destination: string; }' is missing the following properties from type '{ source: string; destination: string; options: CopyActionOptions; globOptions: Pick<Options, "baseNameMatch" | "braceExpansion" | "caseSensitiveMatch" | ... 15 more ... | "unique">; }': options, globOptions
```

Possibly introduced by: https://github.com/gregnb/filemanager-webpack-plugin/pull/111/files#diff-a150fb53afee945f23f3fe7c176007111f3ba81bb0d188af4077d4a0fc4caa37R23-R26

I think `options` and `globOptions` should be optional.
Works fine with 7.0.0-alpha.0

## Your Environment

| Tech                       | Version |
| -------------------------- | ------- |
| filemanager-plugin-webpack |   7.0.0-alpha.1      |
| node                       |     14    |
| OS                         |     macos 12.1    |

**Comment by sibiraj-s** [comment]
<img width="786" alt="Screenshot 2022-02-02 at 6 19 54 PM" src="https://user-images.githubusercontent.com/20282546/152157044-eed7296b-2620-4385-b82a-7e924ce4c5ab.png">

Can you check again. its there...

**Comment by sibiraj-s** [comment]
<img width="229" alt="Screenshot 2022-02-02 at 6 26 23 PM" src="https://user-images.githubusercontent.com/20282546/152158003-50aaa575-c738-4cbd-b205-93154285f20b.png">

I have now fixed the dist tags. previously latest is pointing to alpha. check now?

**Comment by Phil147** [comment]
Turned out to be some caching issues on my end. Thanks for looking into it!
